# Generated by Django 3.1.3 on 2023-10-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('disease_name', models.CharField(max_length=200)),
            ],
        ),
    ]
